# Generated by Django 4.2 on 2023-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='door',
            field=models.ImageField(blank=True, null=True, upload_to='doorstep/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot/'),
        ),
    ]
