# Generated by Django 4.2 on 2023-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userdata_door_alter_userdata_sshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='lat_tude',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='lon_tude',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
