# Generated by Django 4.2 on 2023-05-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userdata_lat_tude_userdata_lon_tude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
